mainpage/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import MyLogoutView, MainView, CalculatorView, registration, ProfileDetailView, ProfileUpdateView,CalculationDetailView, CalculationListView, My_Oreder_CalculationListView
from mainpage import views


app_name = "mainpage"
urlpatterns = [
    path('registration/', registration, name="register"),
    path('calculator/', CalculatorView.as_view(), name="calculator"),
    #path('main/<int:pk>/update/', ProfileUpdateView.as_view(), name="profile_update"),
    path('editprofile/', views.update_profile),
    path('calculation/<int:pk>/', CalculationDetailView.as_view(), ),
    path('calculation_list/', CalculationListView.as_view(), name="calculation"),
    path('mycalculations/', My_Oreder_CalculationListView.as_view(), name="calculation"),
    path('profile/', ProfileDetailView.as_view(), name="profile"),

    path('logout/', MyLogoutView.as_view(), name="logout"),
    path("",
         LoginView.as_view(
             template_name="mainpage/login.html",
             redirect_authenticated_user=True,
         ),
         name="login"),
    path('main/', MainView.as_view(), name="main"),
    ]

site1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('mainpage.urls')),
    path('admin/', admin.site.urls),
]

mainpage/forms.py
from django import forms
from django.forms import ModelForm
from .models import Profile, Branch, Order_Varibles
from django.contrib.auth.models import User


class ProfileForm(ModelForm):
    surname = forms.CharField(label='Фамилия', max_length=100)
    name = forms.CharField(label='Имя', max_length=100)
    middle_name = forms.CharField(label='Отчество', max_length=100)
    email = forms.EmailField(label='Почта', max_length=100)
    organization = forms.CharField(label='Название организации', max_length=100)
    inn = forms.CharField(label='ИНН', max_length=100)
    site = forms.CharField(label="Веб-сайт организации", max_length=100)
    branch = forms.ModelChoiceField(label="Отрасль ведения хозяйственной деятельности", queryset=Branch.objects.all(),
                                    empty_label="")
    country = forms.CharField(label='Страна', max_length=100)
    city = forms.CharField(label='Город', max_length=100)
    position = forms.CharField(label='Должность', max_length=100)

    class Meta:
        model = Profile
        fields = ['surname', 'name', 'middle_name', 'email', 'organization', 'inn',
                  'site', 'branch', 'country', 'city', 'position']


class CalculatorForm(forms.ModelForm):
    class Meta:
        model = Order_Varibles
        fields = ['industry_type', 'organisation_type', 'worker_amount','area_type','area_is_special_economic','business_type','area_yardage','need_water',
                  'need_gas','need_electricity', 'is_patent_use','stanki_name_1','stanki_amount_1','stanki_name_2','stanki_amount_2','stanki_name_3','stanki_amount_3','stanki_name_4','stanki_amount_4', 'transport_sum','other_sum']
        labels = {'industry_type':'Отрасль ведения хозяйственной деятельности',
                  'organisation_type':'Организационно-правовая форма',
        'worker_amount':'Количество сотрудников',
        'area_type':'Территория расположения производства',
        'area_is_special_economic':'Размещение в особой экономической зоне',
        'business_type':'Тип реализации проекта',
        'area_yardage':'Площадь производства, в квадратных метрах',
        'building_yardage':'Площадь здания',
        'need_water':'Необходимо подключение к водопроводу',
                  'need_gas':'Необходимо подключение к газу',
        'need_electricity':'Необходимо подключение к электричеству',
                  'stanki_name_1':'Станки тип 1',
                  'stanki_name_2':'Станки тип 2',
                  'stanki_name_3':'Станки тип 3',
                  'stanki_name_4':'Станки тип 4',

                  'stanki_amount_1': 'Количество станков 1 типа ',
                  'stanki_amount_2': 'Количество станков 2 типа ',
                  'stanki_amount_3': 'Количество станков 3 типа ',
                  'stanki_amount_4': 'Количество станков 4 типа ',
                  'transport_sum': 'Расходы на транспорт',
                  'other_sum':'Иные расходы',

        'is_patent_use':'Использовать патент' }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите логин',

            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите логин',

            }),
            'email': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите логин',

            }),

        }

mainpage/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import TemplateView, UpdateView, CreateView, DetailView, ListView
from .models import Profile, Order_Varibles
from .forms import ProfileForm,CalculatorForm,UserForm
from django import forms
from .pdf_maker import *
from .salary_function import *
from .accounting import *
from .building_area_cost import *

class MyLogoutView(LogoutView):
    next_page = reverse_lazy('mainpage:login')


class MainView(TemplateView):
    template_name = "mainpage/main.html"


class CalculationListView (ListView):
    model=Order_Varibles
    template_name = "mainpage/calculationlist.html"

class My_Oreder_CalculationListView (ListView):
    model=Order_Varibles
    template_name = "mainpage/my_calculationlist.html"

    def get_queryset(self):
        order = Order_Varibles.objects.filter(User_create_order=self.request.user)
        return order


class CalculatorView(CreateView):
    form_class = CalculatorForm

    template_name = "mainpage/calculator.html"
    success_url = '/'

    def form_valid(self, CalculatorForm):
        obj = CalculatorForm.save(commit=False)
        obj.User_create_order = self.request.user
       # salary_fss_pfr=wages(CalculatorForm.cleaned_data['industry_type'], CalculatorForm.cleaned_data['worker_amount'])
        salary_fss_pfr=wages(4, CalculatorForm.cleaned_data['worker_amount'])
        obj.pfr_min=salary_fss_pfr['6 месяцев']['ОПС']
        obj.oms_min=salary_fss_pfr['6 месяцев']['ОМС']
        obj.pfr_max=salary_fss_pfr['Год']['ОПС']
        obj.oms_max=salary_fss_pfr['Год']['ОПС']
        obj.vnim_min=salary_fss_pfr['6 месяцев']['ВНиМ']
        obj.vnim_max=salary_fss_pfr['Год']['ВНиМ']
        obj.ndfl_min=salary_fss_pfr['6 месяцев']['НДФЛ']
        obj.ndfl_max=salary_fss_pfr['Год']['НДФЛ']
        obj.salary_min=salary_fss_pfr['6 месяцев']['Зарплата']
        obj.salary_max=salary_fss_pfr['Год']['Зарплата']
        obj.total_personal_min=salary_fss_pfr['6 месяцев']['Итого']
        obj.total_personal_max=salary_fss_pfr['Год']['Итого']
        if CalculatorForm.cleaned_data['organisation_type'] =='ИП':
            option=1
        else:
            option=2
        accunting= accounting_func(option,CalculatorForm.cleaned_data['worker_amount'])
        try:
            obj.total_AC6 =accunting['ООО (ОСН)']
            obj.total_AC15 =accunting['ООО (УСН 15%, ЕСХН)']
            obj.total_AC_OSN =accunting['ООО (УСН 6%)']
        except:
            obj.total_AC6 = accunting['ИП (ОСН)']
            obj.total_AC15 = accunting['ИП (УСН 15%, ЕСХН)']
            obj.total_AC_OSN = accunting['ИП (УСН 6%)']

        string=str(CalculatorForm.cleaned_data['area_type']).replace('>', '').split(":")
        type_rent=str(CalculatorForm.cleaned_data['business_type']).replace('>', '').split(":")

        building_rent=rent(CalculatorForm.cleaned_data['area_yardage'],string[0],type_rent[0],CalculatorForm.cleaned_data['area_is_special_economic'])
        #obj.building_sum_min = building_rent
        try:
            items = list(building_rent.items())
            if items[0][1]== 'Введены некорректные данные':
                obj.building_sum_min = 0
                building_sum_min = 0
            else:
                obj.building_sum_min=items[0][1]
                building_sum_min = items[0][1]
        except:

            if building_rent == 'Введены некорректные данные':
                obj.building_sum_min =0

            else:
                obj.building_sum_min = building_rent

        try:
            obj.building_sum_max = items[1][1]
        except:
            m=2
        try:
            total_patent=patent(option)
        except:
            total_patent=0

        try:
            registrastion_OOO_IP=registrastion_fee(option)
        except:
            registrastion_OOO_IP=0

        obj.total_registrastion_fee=registrastion_OOO_IP
        obj.total_patent_sum=total_patent



        try:
            type1=str(CalculatorForm.cleaned_data['stanki_name_1']).replace('>', '').split(":")
            amount1=CalculatorForm.cleaned_data['stanki_amount_1']
            stanki_sum1=machinery(type1[0],amount1)
            obj.stanki_sum1=stanki_sum1
        except:
            obj.stanki_name_1=None
            obj.stanki_amount_1=0
            obj.stanki_sum1=0
            stanki_sum1=0

        try:
            type2=CalculatorForm.cleaned_data['stanki_name_2'].replace('>', '').split(":")
            amount2=CalculatorForm.cleaned_data['stanki_amount_2']
            stanki_sum2=machinery(type[0],amount2)
            obj.stanki_sum2 = stanki_sum2
        except:
            obj.stanki_name_2=None
            obj.stanki_amount_2=0
            obj.stanki_sum2=0
            stanki_sum2 = 0
        try:
            type3=CalculatorForm.cleaned_data['stanki_name_3'].replace('>', '').split(":")
            amount3=CalculatorForm.cleaned_data['stanki_amount_3']
            stanki_sum3=machinery(type3[0],amount3)
            obj.stanki_sum3 = stanki_sum3
        except:
            obj.stanki_name_3=None
            obj.stanki_amount_3=0
            obj.stanki_sum3=0
            stanki_sum3 = 0

        try:
            type4=CalculatorForm.cleaned_data['stanki_name_4'].replace('>', '').split(":")
            amount4=CalculatorForm.cleaned_data['stanki_amount_4']
            stanki_sum4=machinery(type4[0],amount4)
            obj.stanki_sum4 = stanki_sum4
        except:
            obj.stanki_name_4=None
            obj.stanki_amount_4=0
            obj.stanki_sum4=0
            stanki_sum4 = 0

        stanki_total_suma=stanki_sum1+stanki_sum2+stanki_sum3+stanki_sum4
        obj.stanki_total_sum = stanki_total_suma

        if option==1:
            rashod_na_account=accunting['ИП (ОСН)']
        else:
            rashod_na_account = accunting['ООО (ОСН)']

        total_sum_personal=salary_fss_pfr['6 месяцев']['Зарплата']+salary_fss_pfr['6 месяцев']['НДФЛ']+ salary_fss_pfr['6 месяцев']['ОПС']+salary_fss_pfr['6 месяцев']['ОМС']
        try:
            total_all_sum=total_sum_personal+stanki_total_suma+total_patent+registrastion_OOO_IP+building_sum_min+CalculatorForm.cleaned_data['other_sum']+CalculatorForm.cleaned_data['transport_sum']+CalculatorForm.cleaned_data['other_sum']+CalculatorForm.cleaned_data['transport_sum']
        except:
            total_all_sum = total_sum_personal + stanki_total_suma + total_patent + registrastion_OOO_IP







        obj.excel_link =make_excel(CalculatorForm.cleaned_data['industry_type'],CalculatorForm.cleaned_data['organisation_type'],CalculatorForm.cleaned_data['worker_amount'],CalculatorForm.cleaned_data['area_type'], salary_fss_pfr,total_sum_personal,building_sum_min,salary_fss_pfr['6 месяцев']['НДФЛ'],rashod_na_account)

        obj.pdf_link = make_invest_pdf(CalculatorForm.cleaned_data['industry_type'],
                                       CalculatorForm.cleaned_data['organisation_type'],
                                       CalculatorForm.cleaned_data['worker_amount'],
                                       CalculatorForm.cleaned_data['area_type'],
                                       salary_fss_pfr['6 месяцев']['ОПС'],
                                       salary_fss_pfr['6 месяцев']['ОМС'],
                                       salary_fss_pfr['Год']['ОПС'],
                                       salary_fss_pfr['Год']['ОПС'],
                                       rashod_na_account,
                                       building_sum_min,
                                       salary_fss_pfr['6 месяцев']['НДФЛ'],
                                       total_sum_personal,
                                       total_all_sum


                                       )

        obj.save()

        newpage=Order_Varibles.objects.filter(User_create_order=self.request.user).last()

        return redirect("/calculation/"+str(newpage.id))



class CalculationDetailView(DetailView):
    model = Order_Varibles
    template_name = "mainpage/one_caluclation.html"


def registration(request):
    if request.method == 'POST':
        form1 = UserCreationForm(request.POST)
        form2 = ProfileForm(request.POST)
        if form1.is_valid() and form2.is_valid():
            form1.save()
            form2.save()
            # получаем имя пользователя и пароль из формы
            username = form1.cleaned_data.get('username')
            password = form1.cleaned_data.get('password1')
            name = form2.cleaned_data.get('name')
            surname = form2.cleaned_data.get('surname')
            middle_name = form2.cleaned_data.get('middle_name')
            email = form2.cleaned_data.get('email')
            organization = form2.cleaned_data.get('organization')
            inn = form2.cleaned_data.get('inn')
            site = form2.cleaned_data.get('site')
            branch = form2.cleaned_data.get('branch')
            country = form2.cleaned_data.get('country')
            city = form2.cleaned_data.get('city')
            position = form2.cleaned_data.get('position')
            # выполняем аутентификацию
            user = authenticate(username=username, password=password)
            login(request, user)
            Profile.objects.create(user=request.user, name=name, surname=surname, middle_name=middle_name,
                                   email=email, organization=organization, inn=inn, site=site, branch=branch,
                                   country=country, city=city, position=position)
            return redirect('/profile')
    else:
        form1 = UserCreationForm()
        form2 = ProfileForm()
    return render(request, 'mainpage/register.html', {'form1': form1, 'form2': form2})

mainpage/templates/mainpage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
  {% load static %}
     <link rel = "icon" type = "image/png" href = "{% static '/images/logoinvest.ico' %}">
    <link href="https://fonts.cdnfonts.com/css/tt-norms-pro" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>





  <style type="text/css">


    *, button {
font-display: optional;
   font-weight: 600;
   font-family: 'TT Norms Pro',sans-serif;
   }
  </style>



</head>
<body>
  <nav class="navbar navbar-expand-lg  border-bottom" style="background-color: #cc2222">
  <div class="container-fluid" >
    <a class="navbar-brand" href="/" style="color: #e3f2fd;"> <img src="{% static '/images/logoinvest.png' %}" alt="" width="50" height="50"></a>
    <button class="navbar-toggler bg-primary"  type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon bi bi-justify text-center" style="color: #fff;"></span>

    </button>
    <div class="collapse navbar-collapse"  id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">



        <li class="nav-item ml-auto">
          <a class="nav-link text-white"  style="" href="/calculator/" tabindex="-1" aria-disabled="true"><b>Калькулятор</b></a>
        </li>



      </ul>


       <div class="navbar-nav align-items-end">









           <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


{% if  request.user.is_authenticated %}
<div class="dropdown">
  <button style="background-color: #cc2222" class="btn btn-primary dropdown-toggle tex-white border-0 " type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
  <i class="bi bi-person-fill"></i> Профиль, {{ request.user }}
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="/profile/">Мой профиль</a></li>
    <li><a class="dropdown-item" href="/editprofile/">Обновить профиль</a></li>

    <li> <a class="nav-link active" style="color:black" href="/logout" tabindex="-1" ><b> Выйти</b></a></li>
  </ul>
</div>
{% else %}
  <a class="nav-link text-white"  href="/login" tabindex="-1" ><b><i class="bi bi-person-fill"></i>
Личный кабинет</b></a>



  {% endif %}




      </div>

    </div>
  </div>
</nav>
    {% block body %}

    {% endblock %}
</body>
</html>

mainpage/templates/mainpage/calculationlist.html
{% extends 'mainpage/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Редактировать профиль
{% endblock %}

{% block body %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="card shadow">
                <div class="container"><br>
<br>
                                    <h1 class="text-center">Все рассчеты</h1>
  {% for item in object_list %}
                    {{ item }}
                    {% endfor %}
<br>
<br><br>
<br>

                </div>

            </div>

<br>
<br>
        </div>
        <div class="col-1"></div>



    </div>




</div>

{% endblock %}

mainpage/templates/mainpage/calculator.html
{% extends 'mainpage/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  Калькулятор
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">

<br><br>
               <h1 class="text-center">Расчет затрат на запуск промышленного производства в городе Москве</h1>
            <div class="card shadow">
                <div class="container">
<br>
                 <form method="POST" action="">
                            {% csrf_token %}
      {{ form|crispy }}
                     <br>
        <button type="submit" class="btn text-white font-weight-bold" style="background-color:#cc2222">Получить результат</button>
    </form>
<br>
<br>
</div>
            </div>
 <br><br>







        </div>
        <div class="col-md-1"></div>









    </div>






</div>


{% endblock %}

mainpage/templates/mainpage/login.html
{% extends 'mainpage/base.html' %}

{% block title %}
  Вход
{% endblock %}

{% block body %}
{% load crispy_forms_tags %}
<br>
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <div class="card shadow">

<div class="container">
     <br>
      <p class="text-center">Авторизация</p>
    <br>

          <form method="post">
    {% csrf_token %}

   {{ form|crispy }}
    <div>
      <p><a href="{% url 'mainpage:register' %}">Регистрация</a></p>
    </div>
    <button class="btn btn-primary" type="submit" style="background-color: #cc2222">Login</button>
  </form>
<br>
<br>
<br>
        </div>
        </div>
            </div>
        <div class="col-md-1"></div>
    </div>
    </div>

<br>
<br>
<br>
<br>
{% endblock %}

mainpage/templates/mainpage/main.html
{% extends 'mainpage/base.html' %}

{% block title %}
  Главная страница
{% endblock %}

{% block body %}
    <h1>Главная страница пользователя: {{ user.username }}</h1>
    <form action="{% url 'mainpage:calculator' %}">
        <button type="submit">Калькулятор</button>
    </form>
    <form action="{% url 'mainpage:profile' pk=user.profile.pk %}">
        <button type="submit">Профиль</button>
    </form>

    <form action="{% url 'mainpage:logout' %}">
        <button type="submit">Выход</button>
    </form>

{% endblock %}

mainpage/templates/mainpage/my_calculationlist.html
{% extends 'mainpage/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Редактировать профиль
{% endblock %}

{% block body %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="card shadow">
                <div class="container"><br>
<br>
                                    <h1 class="text-center">Все расчеты</h1>
<table class="table">

         <thead>
    <tr>
      <th scope="col">Номер расчета</th>
      <th scope="col">Дата</th>
      <th scope="col">Ссылка</th>


    </tr>
  </thead>
                      {% for item in object_list %}
 <tr>
      <td>{{ item.id }}</td>
      <td>{{ item.order_create_date }}</td>
     <td><a href="/calculation/{{ item.id }}"><button class="btn btn-success">Подробности</button> </a></td>
    </tr>





                    {% endfor %}

</table>
<br>
<br><br>
<br>

                </div>

            </div>

<br>
<br>
        </div>
        <div class="col-1"></div>



    </div>




</div>

{% endblock %}

mainpage/templates/mainpage/one_caluclation.html
{% extends 'mainpage/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Редактировать профиль
{% endblock %}

{% block body %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="card shadow">
                <div class="container"><br>
<br>
                                    <h1 class="text-center">Расчет {{ object.id }}</h1>
                  <a href="/media/{{ object.excel_link }}"> <button class="btn btn-info">Скачать финмодель</button></a>
                    <a href="/media/pdf/{{ object.pdf_link }}"> <button class="btn btn-success">Скачать буклет</button></a>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Значение</th>

    </tr>
  </thead>


  <tbody>
    <tr>
          <td>Номер рассчета</td>
      <td>{{ object.id }}</td>
    </tr><tr>
          <td>Округ</td>
      <td>{{ object.area_type_id }}</td>
    </tr>
     <tr>
          <td>Дата расчета </td>
      <td>{{ object.order_create_date|date:"SHORT_DATE_FORMAT" }}</td>
    </tr>
  <tr>
          <td>Площадь производства </td>
      <td>{{ object.area_yardage }}</td>
    </tr>
    <tr>
          <td>Количество работников </td>
      <td>{{ object.worker_amount }}</td>
    </tr>
    <tr>
          <td>Организационно-правовая форма </td>

      <td> {{ object.organisation_type_id}}</td>

    </tr>
    <tr>
          <td>Отрасль </td>
      <td>{{ object.industry_type_id }}</td>
    </tr>
    <tr>
          <td>Потребность в газе </td>
      <td>{{ object.need_gas }}</td>
    </tr>
    <tr>
          <td>Потребность в электричестве </td>
      <td>{{ object.need_electricity }}</td>
    </tr>

  </tbody>
</table>


<br>
<br><br>
<br>

                </div>

            </div>

<br>
<br>
        </div>
        <div class="col-1"></div>



    </div>




</div>

{% endblock %}

mainpage/templates/mainpage/profile_form.html
{% extends 'mainpage/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Редактировать профиль
{% endblock %}

{% block body %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="card shadow">
                <div class="container"><br>
<br>
                                    <h1 class="text-center">Редактировать профиль</h1>


    <form method="post">
        {% csrf_token %}

          {{ profile_form|crispy }}
        <button class='btn text-white font-weight-bold' style="background-color: #cc2222" type="submit" >Сохранить изменения</button>
    </form>
<br>
<br><br>
<br>

                </div>

            </div>

<br>
<br>
        </div>
        <div class="col-1"></div>



    </div>




</div>

{% endblock %}

mainpage/templates/mainpage/register.html
{% extends 'mainpage/base.html' %}

{% block title %}
  Регистрация
{% endblock %}

{% block body %}
{% load crispy_forms_tags %}
<br>
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">




            <div class="card shadow">
                <br>
             <h1 class="text-center">Регистрация</h1>
                <div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form2|crispy }}
        {{ form1|crispy }}
        <input type="submit" class="btn btn-primary" style="background-color: #cc2222" value="Регистрация">
    </form>
                    <br>
                    <br>
</div>
</div>




        </div>
        <div class="col-md-1"></div>

    </div>

</div>
<br>
<br>
<br>
<br>
{% endblock %}